<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class BlogPostCreateRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            "title"=>"required|min:5|max:200|unique:blog_posts",
	        "slug"=>"max:200",
	        "content_raw"=>"required|string|min:5|max:10000",
	        "category_id"=>"required|integer|exists:blog_categories,id"
        ];
    }


	/**
	 * @return array
	 * translate  messages about errors
	 * it is only one way/  main vay translate in file lang in the folder resource
	 */
    public  function  messages() {
	  //  return parent::messages(); // TODO: Change the autogenerated stub
//$defaultMessages = parent::messages();

    return [
        // "title.required"=>"Введите :attribute статьи",
         "title.required"=>"Введите :attribute статьи",
	    "title.min" =>":attribute - минимальная длина  должна быть не менее [:min]  символов",
	     "content_raw.min"=>"Минимальная длина статьи [:min] символов"
    ];

    }

    public  function  attributes() {
	   // return parent::attributes(); // TODO: Change the autogenerated stub
  // $defaultAttributes = parent::attributes();

	   return[
    	"title"=>"Заголовок"
   ];

//return array_merge($defaultAttributes ,$attributes );
//return $defaultAttributes;
//return $attributes;
    }





}
